MyAppBlogBundle:
    resource: "@MyAppBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

myapp:
  resource: "@MyAppFilmothequeBundle/Resources/config/routing.yml"
  prefix: /myapp

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
