parameters:
#    my_app_blog.example.class: MyApp\BlogBundle\Example

services:
#    my_app_blog.example:
#        class: %my_app_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
